const expertise = [
    { name: 'Cloud Engineer', category: 'Technology' },
    { name: 'Software Engineer', category: 'Technology' },
    { name: 'Data Scientist', category: 'Technology' },
    { name: 'Data Analyst', category: 'Technology' },
    { name: 'Data Engineer', category: 'Technology' },
    { name: 'Product Manager', category: 'Technology' },
    { name: 'UX Designer', category: 'Technology' },
    { name: 'UI Designer', category: 'Technology' },
    { name: 'Frontend Engineer', category: 'Technology' },
    { name: 'Backend Engineer', category: 'Technology' },
    { name: 'Fullstack Engineer', category: 'Technology' },
    { name: 'DevOps', category: 'Technology' },
    { name: 'Cyber Security Engineer', category: 'Technology' },
    { name: 'Technical Writer', category: 'Technology' },
    { name: 'Technical Recruiter', category: 'Technology' },
    { name: 'Account Executive', category: 'Technology' },
    { name: 'Account Manager', category: 'Technology' },
    { name: 'Network Adminsitrator', category: 'Technology' },
    { name: 'Network Engineer', category: 'Technology' },
    { name: 'Network Architect', category: 'Technology' },
    { name: 'Network Manager', category: 'Technology' },
    { name: 'Network Director', category: 'Technology' },
    { name: 'Network Security', category: 'Technology' },
    { name: 'Network Recruiter', category: 'Technology' },
    { name: 'Network Analyst', category: 'Technology' },
    { name: 'Network Engineer', category: 'Technology' },
    { name: 'Network Architect', category: 'Technology' },
    { name: 'Network Director', category: 'Technology' },
    { name: 'Graphic Designer', category: 'Technology' },
    { name: 'Graphic Artist', category: 'Technology' },
    { name: 'Graphic Manager', category: 'Technology' },
    { name: 'Graphic Director', category: 'Technology' },
    { name: 'Graphic Operations', category: 'Technology' },
    { name: 'Graphic Recruiter', category: 'Technology' },
    { name: 'Video Editor', category: 'Technology' },
    { name: 'Video Producer', category: 'Technology' },
    { name: 'Video Manager', category: 'Technology' },
    { name: 'Video Director', category: 'Technology' },
    { name: 'Sales Representative', category: 'Marketing' },
    { name: 'Sales Manager', category: 'Marketing' },
    { name: 'Sales Director', category: 'Marketing' },
    { name: 'Sales Operations', category: 'Marketing' },
    { name: 'Sales Development', category: 'Marketing' },
    { name: 'Sales Trainer', category: 'Marketing' },
    { name: 'Sales Recruiter', category: 'Marketing' },
    { name: 'Sales Analyst', category: 'Marketing' },
    { name: 'Sales Engineer', category: 'Marketing' },
    { name: 'Marketing Manager', category: 'Marketing' },
    { name: 'Marketing Director', category: 'Marketing' },
    { name: 'Marketing VP', category: 'Marketing' },
    { name: 'Marketing Operations', category: 'Marketing' },
    { name: 'Marketing Enablement', category: 'Marketing' },
    { name: 'Marketing Development', category: 'Marketing' },
    { name: 'Marketing Trainer', category: 'Marketing' },
    { name: 'Marketing Recruiter', category: 'Marketing' },
    { name: 'Marketing Analyst', category: 'Marketing' },
    { name: 'Marketing Engineer', category: 'Marketing' },
    { name: 'Marketing Architect', category: 'Marketing' },
    { name: 'Marketing Manager', category: 'Marketing' },

]


export default expertise;