
const locations = [
  //aurora
  { name: "Baler, Aurora" },
  { name: "Casiguran, Aurora" },
  { name: "Dilasag, Aurora" },
  { name: "Dinalungan, Aurora" },
  { name: "Dingalan, Aurora" },
  { name: "Dipaculao, Aurora" },
  { name: "Maria Aurora, Aurora" },
  { name: "San Luis, Aurora" },
  { name: "Dipaculao, Aurora" },
  { name: "Dingalan, Aurora" },

  //bataan
  { name: "Dinalupihan, Bataan" },
  { name: "Hermosa, Bataan" },
  { name: "Limay, Bataan" },
  { name: "Mariveles, Bataan" },
  { name: "Morong, Bataan" },
  { name: "Orani, Bataan" },
  { name: "Orion, Bataan" },
  { name: "Pilar, Bataan" },
  { name: "Samal, Bataan" },
  { name: "Balanga, Bataan" },
  { name: "Abucay, Bataan" },
  { name: "Bagac, Bataan" },
  

  //bulacan
  { name: "Malolos, Bulacan" },
  { name: "Meycauayan, Bulacan" },
  { name: "Marilao, Bulacan" },
  { name: "Bocaue, Bulacan" },
  { name: "Baliuag, Bulacan" },
  { name: "San Jose del Monte, Bulacan" },
  { name: "Santa Maria, Bulacan" },
  { name: "Guiguinto, Bulacan" },
  { name: "Plaridel, Bulacan" },
  { name: "Pulilan, Bulacan" },
  { name: "Hagonoy, Bulacan" },
  { name: "Paombong, Bulacan" },
  { name: "San Miguel, Bulacan" },
  { name: "San Ildefonso, Bulacan" },
  { name: "Bustos, Bulacan" },
  { name: "Calumpit, Bulacan" },
  { name: "Angat, Bulacan" },
  { name: "San Rafael, Bulacan" },
  { name: "Norzagaray, Bulacan" },
  { name: "Doña Remedios Trinidad, Bulacan" },
  { name: "San Jose del Monte, Bulacan" },
  { name: "San Miguel, Bulacan" },
  { name: "San Ildefonso, Bulacan" },
  
  //nueva ecija
  { name: "Cabanatuan, Nueva Ecija" },
  { name: "Gapan, Nueva Ecija" },
  { name: "Palayan, Nueva Ecija" },
  { name: "San Jose, Nueva Ecija" },
  { name: "Santa Rosa, Nueva Ecija" },
  { name: "Talavera, Nueva Ecija" },
  { name: "Science City of Muñoz, Nueva Ecija" },
  { name: "Cuyapo, Nueva Ecija" },
  { name: "Laur, Nueva Ecija" },
  { name: "Licab, Nueva Ecija" },
  { name: "Llanera, Nueva Ecija" },
  { name: "Rizal, Nueva Ecija" },
  { name: "San Antonio, Nueva Ecija" },
  { name: "San Isidro, Nueva Ecija" },
  { name: "Aliaga, Nueva Ecija" },
  { name: "Bongabon, Nueva Ecija" },
  { name: "Gabaldon, Nueva Ecija" },
  { name: "General Mamerto Natividad, Nueva Ecija" },
  { name: "General Tinio, Nueva Ecija" },
  { name: "Jaen, Nueva Ecija" },
  { name: "Lupao, Nueva Ecija" },
  { name: "Nampicuan, Nueva Ecija" },
  { name: "Pantabangan, Nueva Ecija" },
  { name: "Peñaranda, Nueva Ecija" },
  { name: "Quezon, Nueva Ecija" },
  { name: "Rizal, Nueva Ecija" },
  { name: "San Leonardo, Nueva Ecija" },
  { name: "Santa Rosa, Nueva Ecija" },
  { name: "Santo Domingo, Nueva Ecija" },
  { name: "Talugtug, Nueva Ecija" },
  { name: "Zaragoza, Nueva Ecija" },
  //pampanga
  { name: "Angeles, Pampanga" },
  { name: "Candaba, Pampanga" },
  { name: "San Fernando, Pampanga" },
  { name: "Sto.Tomas , Pampanga" },
  { name: "Santa Ana, Pampanga" },
  { name: "Mexico, Pampanga" },
  { name: "San Simon, Pampanga" },
  { name: "San Luis, Pampanga" },
  { name: "Apalit, Pampanga" },
  { name: "Minalin, Pampanga" },
  { name: "Guagua, Pampanga" },
  { name: "Sasmuan, Pampanga" },
  { name: "Lubao, Pampanga" },
  { name: "Porac, Pampanga" },
  { name: "Floridablanca, Pampanga" },
  { name: "Bacolor, Pampanga" },
  { name: "Arayat, Pampanga" },
  { name: "Magalang, Pampanga" },
  { name: "Mabalacat, Pampanga" },
  { name: "Masantol, Pampanga" },
  { name: "Macabebe, Pampanga" },

  //tarlac
  { name: "Anao, Tarlac" },
  { name: "Bamban, Tarlac" },
  { name: "Camiling, Tarlac" },
  { name: "Capas, Tarlac" },
  { name: "Concepcion, Tarlac" },
  { name: "Gerona, Tarlac" },
  { name: "La Paz, Tarlac" },
  { name: "Mayantoc, Tarlac" },
  { name: "Moncada, Tarlac" },
  { name: "Paniqui, Tarlac" },
  { name: "Pura, Tarlac" },
  { name: "Ramos, Tarlac" },
  { name: "San Clemente, Tarlac" },
  { name: "San Jose, Tarlac" },
  { name: "San Manuel, Tarlac" },
  { name: "Santa Ignacia, Tarlac" },
  { name: "Victoria, Tarlac" },
  { name: "Tarlac City, Tarlac" },
  //zambales
  { name: "Olongapo, Zambales" },
  { name: "Subic, Zambales" },
  { name: "Botolan, Zambales" },
  { name: "Cabangan, Zambales" },
  { name: "Candelaria, Zambales" },
  { name: "Castillejos, Zambales" },
  { name: "Iba, Zambales" },
  { name: "Masinloc, Zambales" },
  { name: "Palauig, Zambales" },
  { name: "San Antonio, Zambales" },
  { name: "San Felipe, Zambales" },
  { name: "San Marcelino, Zambales" },
  { name: "San Narciso, Zambales" },
  { name: "Santa Cruz, Zambales" },
  { name: "Subic, Zambales" },

];

export default locations