const tags = [
  { name: "Programming", category: "Technology" },
  { name: "Cryptocurrency", category: "Business" },
  { name: "Web Development", category: "Technology" },
  { name: "Data Science", category: "Technology" },
  { name: "Artificial Intelligence", category: "Technology" },
  { name: "Marketing", category: "Business" },
  { name: "Fitness", category: "Health" },
  { name: "Physics", category: "Science" },
  { name: "Dance", category: "Arts" },
  { name: "Italian Cuisine", category: "Cooking" },
  { name: "Football", category: "Sports" },
  { name: "Backpacking", category: "Travel" },
  { name: "Blockchain", category: "Business" },
  { name: "Mobile App Development", category: "Technology" },
  { name: "Finance", category: "Business" },
  { name: "Mental Health", category: "Health" },
  { name: "Chemistry", category: "Science" },
  { name: "Music", category: "Arts" },
  { name: "BBQ", category: "Cooking" },
  { name: "Basketball", category: "Sports" },
  { name: "Luxury Travel", category: "Travel" },
  { name: "Python", category: "Technology" },
  { name: "Entrepreneurship", category: "Business" },
  { name: "Nutrition", category: "Health" },
  { name: "Biology", category: "Science" },
  { name: "Literature", category: "Arts" },
  { name: "Vegan Cooking", category: "Cooking" },
  { name: "Tennis", category: "Sports" },
  { name: "Adventure Travel", category: "Travel" },
  { name: "Computer Science", category: "Technology" },
  { name: "Economics", category: "Business" },
  { name: "Yoga", category: "Health" },
  { name: "Astronomy", category: "Science" },
  { name: "Theater", category: "Arts" },
  { name: "Sushi Making", category: "Cooking" },
  { name: "Swimming", category: "Sports" },
  { name: "Solo Travel", category: "Travel" },
  { name: "JavaScript", category: "Technology" },
  { name: "Accounting", category: "Business" },
  { name: "Running", category: "Sports" },
  { name: "Geology", category: "Science" },
  { name: "Poetry", category: "Arts" },
  { name: "Mexican Cuisine", category: "Cooking" },
  { name: "Golf", category: "Sports" },
  { name: "Culinary Arts", category: "Cooking" },
  { name: "Boxing", category: "Sports" },
  { name: "Hiking", category: "Travel" },
  { name: "Art History", category: "Arts" },
  { name: "Photography", category: "Arts" },
  { name: "Machine Learning", category: "Technology" },
  { name: "Startups", category: "Business" },
  { name: "Zumba", category: "Health" },
  { name: "Ecology", category: "Science" },
  { name: "Fashion Design", category: "Arts" },
  { name: "Greek Cuisine", category: "Cooking" },
  { name: "Table Tennis", category: "Sports" },
  { name: "Wine Tasting", category: "Cooking" },
  { name: "Rock Climbing", category: "Sports" },
  { name: "History", category: "Arts" },
  { name: "Sculpture", category: "Arts" },
  { name: "Robotics", category: "Technology" },
  { name: "Small Business", category: "Business" },
  { name: "Meditation", category: "Health" },
  { name: "Environmental Science", category: "Science" },
  { name: "Drama", category: "Arts" },
  { name: "Indian Cuisine", category: "Cooking" },
  { name: "Surfing", category: "Sports" },
  { name: "Craft Beer", category: "Cooking" },
  { name: "Archery", category: "Sports" },
  { name: "World History", category: "Arts" },
  { name: "Painting", category: "Arts" }
]

export default tags